import json
import os
from pathlib import Path


class ForgeStub:
    def __init__(self, workspace_root: str | Path | None = None):
        self.workspace_root = self._resolve_workspace_root(workspace_root)
        self.output_dir = self._resolve_output_dir()

    def _resolve_workspace_root(self, workspace_root: str | Path | None) -> Path:
        if workspace_root:
            return Path(workspace_root).expanduser().resolve()

        env_root = os.getenv("AKASHA_HOME")
        if env_root:
            return Path(env_root).expanduser().resolve()

        return Path.home().resolve()

    def _resolve_output_dir(self) -> Path:
        preferred = self.workspace_root / "akasha-discovery" / "build_outputs"
        if preferred.parent.exists() or self.workspace_root == Path.home().resolve():
            return preferred

        local = Path(__file__).resolve().parents[2] / "build_outputs"
        return local

    def _normalize_hypothesis(self, hypothesis: dict) -> dict:
        normalized = dict(hypothesis)
        normalized.setdefault("gap_type", "unclassified")
        normalized.setdefault("gap_score", 0.0)
        normalized.setdefault("reason", "No explicit reason supplied.")
        normalized.setdefault("proposal", f"Review '{normalized.get('target', 'unknown')}'")
        normalized.setdefault("suggestions", ["Review candidate before materializing"])

        if "target" not in normalized:
            raise ValueError("Hypothesis must include a 'target'.")

        return normalized

    def build_proposal(self, hypothesis: dict) -> dict:
        hypothesis = self._normalize_hypothesis(hypothesis)
        gap_type = hypothesis.get("gap_type")

        if gap_type in ("isolated",):
            action = "flag_for_review"
            repo_candidate = None

        elif gap_type in ("structural_sink",):
            action = "propose_extension"
            repo_candidate = f"akasha-{hypothesis['target']}"

        elif gap_type == "intentional_terminal":
            action = "flag_for_review"
            repo_candidate = None

        elif gap_type == "unclassified":
            action = "flag_for_review"
            repo_candidate = None

        else:
            action = "flag_for_review"
            repo_candidate = None

        return {
            "target": hypothesis["target"],
            "gap_type": hypothesis["gap_type"],
            "reason": hypothesis["reason"],
            "gap_score": hypothesis["gap_score"],
            "action": action,
            "source_proposal": hypothesis["proposal"],
            "recommended_action": (
                f"Create exploratory module for '{hypothesis['target']}'"
                if repo_candidate else f"Review '{hypothesis['target']}' before materializing"
            ),
            "repo_candidate": repo_candidate,
            "files_to_create": [
                "README.md",
                "repo-manifest.yaml",
                "NOTES.md",
            ] if repo_candidate else [],
            "next_steps": hypothesis["suggestions"],
        }

    def save_build_plan(self, plan: dict) -> str:
        self.output_dir.mkdir(parents=True, exist_ok=True)
        filename = f"{plan['target']}_build_plan.json"
        path = self.output_dir / filename

        path.write_text(json.dumps(plan, indent=2), encoding="utf-8")
        return str(path)

    def materialize(self, plan: dict):
        repo_name = plan.get("repo_candidate")

        if not repo_name:
            return

        repo_path = self.workspace_root / repo_name

        if repo_path.exists():
            print(f"[Forge] Repo already exists: {repo_name}")
            return

        print(f"[Forge] Creating repo: {repo_name}")
        repo_path.mkdir(parents=True)

        (repo_path / "README.md").write_text(
            f"""# {repo_name}

Exploratory module generated by Akasha Forge.

---

This repository participates in the Akasha ecosystem and is described by repo-manifest.yaml.
""",
            encoding="utf-8",
        )

        (repo_path / "repo-manifest.yaml").write_text(
            f"""name: {repo_name}
domain: exploratory
status: draft
""",
            encoding="utf-8",
        )

        (repo_path / "NOTES.md").write_text(
            f"""# Notes

This module was generated in response to a discovery gap:

Target: {plan['target']}
Reason: {plan['reason']}
""",
            encoding="utf-8",
        )

        print(f"[Forge] Scaffold created at {repo_path}")
