import json
from pathlib import Path


class ForgeStub:

    OUTPUT_DIR = Path.home() / "akasha-discovery" / "build_outputs"

    def build_proposal(self, hypothesis: dict) -> dict:
        gap_type = hypothesis.get("gap_type")

        if gap_type in ("isolated",):
            action = "flag_for_review"
            repo_candidate = None

        elif gap_type in ("structural_sink",):
            action = "propose_extension"
            repo_candidate = f"akasha-{hypothesis['target']}"

        elif gap_type == "intentional_terminal":
            action = "flag_for_review"
            repo_candidate = None

        else:
            action = "flag_for_review"
            repo_candidate = None

        return {
            "target": hypothesis["target"],
            "gap_type": hypothesis["gap_type"],
            "reason": hypothesis["reason"],
            "gap_score": hypothesis["gap_score"],
            "action": action,
            "source_proposal": hypothesis["proposal"],
            "recommended_action": (
                f"Create exploratory module for '{hypothesis['target']}'"
                if repo_candidate else f"Review '{hypothesis['target']}' before materializing"
            ),
            "repo_candidate": repo_candidate,
            "files_to_create": [
                "README.md",
                "repo-manifest.yaml",
                "NOTES.md"
            ] if repo_candidate else [],
            "next_steps": hypothesis["suggestions"]
        }

    def save_build_plan(self, plan: dict) -> str:
        self.OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        filename = f"{plan['target']}_build_plan.json"
        path = self.OUTPUT_DIR / filename

        path.write_text(json.dumps(plan, indent=2))
        return str(path)

    def materialize(self, plan: dict):
        repo_name = plan.get("repo_candidate")

        if not repo_name:
            return

        repo_path = Path.home() / repo_name

        if repo_path.exists():
            print(f"[Forge] Repo already exists: {repo_name}")
            return

        print(f"[Forge] Creating repo: {repo_name}")
        repo_path.mkdir(parents=True)

        # README
        (repo_path / "README.md").write_text(f"""# {repo_name}

Exploratory module generated by Akasha Forge.

---

This repository participates in the Akasha ecosystem and is described by repo-manifest.yaml.
""")

        # manifest
        (repo_path / "repo-manifest.yaml").write_text(f"""name: {repo_name}
domain: exploratory
status: draft
""")

        # notes
        (repo_path / "NOTES.md").write_text(f"""# Notes

This module was generated in response to a discovery gap:

Target: {plan['target']}
Reason: {plan['reason']}
""")

        print(f"[Forge] Scaffold created at ~/{repo_name}")
